<?php
/**
 * This file is part of True Loaded.
 *
 * @link http://www.holbi.co.uk
 * @copyright Copyright (c) 2005 Holbi Group LTD
 *
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 */

namespace common\api\models\Soap\Store;


use common\api\models\Soap\SoapModel;

class AdminMember extends SoapModel
{

    /**
     * @var integer {nillable = 0, minOccurs=0, maxOccurs = 1}
     * @soap
     */
    public $admin_id;

    /**
     * @var string {nillable = 0, minOccurs=0, maxOccurs = 1}
     * @soap
     */
    public $admin_firstname;

    /**
     * @var string {nillable = 0, minOccurs=0, maxOccurs = 1}
     * @soap
     */
    public $admin_lastname;

    /**
     * @var string {nillable = 0, minOccurs=0, maxOccurs = 1}
     * @soap
     */
    public $admin_email_address;

    /**
     * @var string {nillable = 0, minOccurs=0, maxOccurs = 1}
     * @soap
     */
    public $admin_password;

    /**
     * @var string {nillable = 0, minOccurs=0, maxOccurs = 1}
     * @soap
     */
    public $admin_created;

    /**
     * @var datetime {nillable = 0, minOccurs=0, maxOccurs = 1}
     * @soap
     */
    public $admin_modified;

    /**
     * @var datetime {nillable = 0, minOccurs=0, maxOccurs = 1}
     * @soap
     */
    public $admin_logdate;

    /**
     * @var integer {nillable = 0, minOccurs=0, maxOccurs = 1}
     * @soap
     */
    public $admin_lognum;
/*
//?? public $avatar              |
login_failture      | 0
login_failture_ip   |
login_failture_date | 2018-07-16 10:51:47
*/

    /**
     * @var integer {nillable = 0, minOccurs=0, maxOccurs = 1}
     * @soap
     */
    public $access_levels_id;

/*
    public $admin_persmissions  | None
additional_info     |
reset_ip            | None
reset_date          | None
public $languages           | en
public $admin_username      |
pin                 | None
customers_id        | 0
device_hash         | ee2391d42bea950a64fc96c1fa73738e
chat_email_address  |
chat_password       | 12345
pos_platform_id     | 0
pos_currency_id
*/

    public function __get($name)
    {
        echo '<pre>'; var_dump($name); echo '</pre>'; die;
        return parent::__get($name); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getAdminPassword(): string
    {
        echo '<pre>'; var_dump('2222'); echo '</pre>'; die;
        return $this->admin_password;
    }

}