<?php
/**
 * This file is part of True Loaded.
 *
 * @link http://www.holbi.co.uk
 * @copyright Copyright (c) 2005 Holbi Group LTD
 *
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 */

namespace common\api\models\Soap\Theme;

use common\api\models\Soap\SoapModel;

class ThemeRemoveResponse extends SoapModel
{
    /**
     * @var integer
     */
    public $themeId;

    /**
     * @var string
     * @soap
     */
    public $status = 'OK';

    /**
     * @var \common\api\models\Soap\ArrayOfMessages Array of Messages {nillable = 0, minOccurs=1, maxOccurs = 1}
     * @soap
     */
    public $messages = [];

    public function build()
    {
        if ( $this->themeId ) {
            $theme = \common\models\Themes::findOne([
                'id' => (int)$this->themeId,
            ]);
            if ( $theme ) {
                $theme->delete();
            }else{
                $this->error('Theme not found', 'NOT_FOUND');
            }
        }else{
            $this->error('themeId required');
        }
        parent::build(); // TODO: Change the autogenerated stub
    }


}